import urllib.request
import os
import re
from urllib.parse import quote

def fetch_m3u(url):
    """Fetches the fully populated M3U playlist from the source URL."""
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(req, timeout=15) as resp:
        return resp.read().decode('utf-8')

def parse_and_rebrand_m3u(m3u_content, output_file):
    """Parses the M3U, rebrands to Gmax, updates User-Agent, and writes to output."""
    lines = m3u_content.splitlines()
    out_lines = ['#EXTM3U']
    user_agent = 'GmaxHub'
    
    current_extinf = None
    current_props = []
    channel_count = 0
    
    for line in lines:
        line = line.strip()
        
        # Skip empty lines and the initial #EXTM3U header
        if not line or line.startswith('#EXTM3U'):
            continue
        
        # Skip cosmetic comment lines generated by the source (e.g., "# JHS Channels...")
        if line.startswith('# ') or line == '#':
            continue
            
        if line.startswith('#EXTINF'):
            current_extinf = line
            current_props = []
        elif line.startswith('#'):
            # Collect all tags like #EXTVLCOPT, #EXTHTTP, #KODIPROP, etc.
            current_props.append(line)
        else:
            # When a stream URL is found, process the channel block
            if current_extinf:
                # 1. Extract metadata from the original #EXTINF line
                name_match = re.search(r'tvg-name="([^"]+)"', current_extinf)
                logo_match = re.search(r'tvg-logo="([^"]+)"', current_extinf)
                group_match = re.search(r'group-title="([^"]+)"', current_extinf)
                
                name = name_match.group(1) if name_match else "Unknown"
                logo = logo_match.group(1) if logo_match else ""
                group = group_match.group(1) if group_match else "Other"
                
                parts = current_extinf.split(',')
                display_name = parts[1].strip() if len(parts) > 1 else name
                
                # Prevent duplication if the script runs on a file that already has branding
                name = name.replace(" | Gmax", "").strip()
                display_name = display_name.replace(" | Gmax", "").strip()
                
                # 2. Append the rebranded #EXTINF line
                out_lines.append(f'#EXTINF:-1 tvg-name="{name} | Gmax" tvg-logo="{logo}" group-title="{group}", {display_name} | Gmax')
                
                # 3. Append properties, injecting the custom user-agent
                for prop in current_props:
                    if prop.startswith('#EXTVLCOPT:http-user-agent='):
                        out_lines.append(f'#EXTVLCOPT:http-user-agent={user_agent}')
                    else:
                        out_lines.append(prop)
                
                # 4. Modify the user-agent directly in the URL parameters (if it exists)
                url = line
                url = re.sub(r'(?i)(user-agent=)[^&]+', lambda m: m.group(1) + quote(user_agent), url)
                out_lines.append(url)
                
                # Mark channel as processed and reset blocks
                channel_count += 1
                current_extinf = None
                current_props = []

    # Automatically create the Playlists folder if it doesn't exist yet
    os.makedirs(os.path.dirname(output_file), exist_ok=True)

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(out_lines))
        
    return channel_count

def main():
    # New direct M3U source containing all channels, cookies, and tags
    m3u_url = 'https://premiumplugx.com/htt/hot.php?playlist=1'
    output = 'Playlists/digital.m3u'

    try:
        print("Fetching full playlist from URL...")
        m3u_content = fetch_m3u(m3u_url)
        count = parse_and_rebrand_m3u(m3u_content, output)
        print(f'Successfully generated {output} with {count} rebranded channels')
    except Exception as e:
        print(f'Error: {e}')

if __name__ == '__main__':
    main()
